import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/comoponent/footer/Footer";
import Navbar from "@/comoponent/navbar/Navbar";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={inter.className}>
        <div className="container">
            <Navbar />
            {children}
            <Footer />
            </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
